const beatSequenceDummy = [
  {
    username: "user0",
    name: "user0-beat0",
    tempo: 65,
    beatGrid: [
      {
        instrument: "601b73cfcb84de34a9b825c5",
        beatRow: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      {
        instrument: "601b73cfcb84de34a9b825c7",
        beatRow: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    ],
    status: "Active",
  },
  {
    username: "user1",
    name: "user1",
    tempo: 65,
    beatGrid: [
      {
        instrument: "601b73cfcb84de34a9b825c5",
        beatRow: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      {
        instrument: "601b73cfcb84de34a9b825c7",
        beatRow: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    ],
    status: "Active",
  },
  {
    username: "user2",
    name: "user2",
    tempo: 500,
    beatGrid: [
      {
        instrument: "601b73cfcb84de34a9b825c5",
        beatRow: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      {
        instrument: "601b73cfcb84de34a9b825c7",
        beatRow: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    ],
    status: "Active",
  },
  {
    username: "user1",
    name: "ublah",
    tempo: 10,
    beatGrid: [
      {
        instrument: "601b73cfcb84de34a9b825c5",
        beatRow: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      {
        instrument: "601b73cfcb84de34a9b825c7",
        beatRow: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    ],
    status: "Active",
  },
  {
    username: "user0",
    name: "user0-beat1",
    tempo: 120,
    beatGrid: [
      {
        instrument: "601b73cfcb84de34a9b825c5",
        beatRow: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      {
        instrument: "601b73cfcb84de34a9b825c7",
        beatRow: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    ],
    status: "Active",
  },
];

module.exports = beatSequenceDummy;
